name: Dialogue Count S3 Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic
    defaultValue: dialogue-counter
    required: true
  - name: s3_bucket
    inputType: FreeText
    description: AWS S3 bucket name
    defaultValue: hackathon-quix-tun
    required: true
  - name: AWS_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: aws_access_key
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: aws_secret_access_key
    required: true
  - name: AWS_REGION
    inputType: FreeText
    description: ''
    defaultValue: eu-west-2
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
