name: Dialogue Count S3 Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic
    defaultValue: dialogue-counter
    required: true
  - name: s3_bucket
    inputType: FreeText
    description: AWS S3 bucket name
    defaultValue: hackathon-quix-tun
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
