name: Dialogue Count S3 Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic
    defaultValue: dialogue-counter
    required: true
  - name: s3_bucket
    inputType: FreeText
    description: AWS S3 bucket name
    defaultValue: hackathon-quix-tun
    required: true
  - name: s3_folder_per_stream
    inputType: FreeText
    description: Flag to save different streams to different S3 folders.
    defaultValue: false
    required: false
  - name: suffix
    inputType: FreeText
    description: File suffix (e.g. file type extension)
    defaultValue: .csv
    required: false
  - name: timezone
    inputType: FreeText
    description: Timezone from the IANA Time Zone Database (e.g. Asia/Singapore) for orchestrating time-based batching and file naming.
    defaultValue: GMT
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
