name: S3 Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic
    defaultValue: dialogue-censored
    required: true
  - name: s3_bucket
    inputType: FreeText
    description: AWS S3 bucket name
    defaultValue: hackathon-quix-tun
    required: true
  - name: timezone
    inputType: FreeText
    description: Timezone from the IANA Time Zone Database (e.g. Asia/Singapore) for orchestrating time-based batching and file naming.
    defaultValue: GMT
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: aws_secret_access_key
    required: false
  - name: AWS_REGION
    inputType: FreeText
    description: ''
    defaultValue: eu-west-2
    required: false
  - name: AWS_DEFAULT_REGION
    inputType: FreeText
    description: ''
    defaultValue: eu-west-2
    required: false
  - name: AWS_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: aws_access_key
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
