name: S3 Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic
    defaultValue: dialogue-censored
    required: true
  - name: batch_msg_count
    inputType: FreeText
    description: Message count in the batch (0 saves data as they arrive, -1 disables batching based on message count)
    defaultValue: 1
    required: false
  - name: parameters
    inputType: FreeText
    description: Comma separated list of parameters to look for in the received data
    defaultValue: none
    required: true
  - name: s3_bucket
    inputType: FreeText
    description: AWS S3 bucket name
    defaultValue: hackathon-quix-tun
    required: true
  - name: prefix
    inputType: FreeText
    description: File name prefix
    defaultValue: ''
    required: false
  - name: s3_folder
    inputType: FreeText
    description: Name of the S3 folder to save to
    defaultValue: ''
    required: false
  - name: s3_folder_per_stream
    inputType: FreeText
    description: Flag to save different streams to different S3 folders.
    defaultValue: false
    required: false
  - name: suffix
    inputType: FreeText
    description: File suffix (e.g. file type extension)
    defaultValue: .csv
    required: false
  - name: timezone
    inputType: FreeText
    description: Timezone from the IANA Time Zone Database (e.g. Asia/Singapore) for orchestrating time-based batching and file naming.
    defaultValue: GMT
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: aws_secret_access_key
    required: false
  - name: AWS_REGION
    inputType: FreeText
    description: ''
    defaultValue: eu-west-2
    required: false
  - name: AWS_DEFAULT_REGION
    inputType: FreeText
    description: ''
    defaultValue: eu-west-2
    required: false
  - name: AWS_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: aws_access_key
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
