name: Redis Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: dialogue-censored
    required: true
  - name: redis_host
    inputType: FreeText
    description: Host address for the Redis instance
    defaultValue: redis-34fd767f-stereosky-ad4e.a.aivencloud.com
    required: true
  - name: redis_port
    inputType: FreeText
    description: Port for the Redis instance
    defaultValue: 6379
    required: true
  - name: redis_password
    inputType: FreeText
    description: Password for the Redis instance
    defaultValue: ''
    required: false
  - name: redis_username
    inputType: FreeText
    description: Username for the Redis instance
    defaultValue: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
